// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsMicroservice;

#nullable disable

namespace ProductsMicroservice.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240702120657_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("versionid");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currencycode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string[]>("ExcludedCountries")
                        .HasColumnType("text[]")
                        .HasColumnName("excludedcountries");

                    b.Property<string>("FriendlyUrl")
                        .HasColumnType("text")
                        .HasColumnName("friendlyurl");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("isarchived");

                    b.Property<bool>("IsDiamond")
                        .HasColumnType("boolean")
                        .HasColumnName("isdiamond");

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("isoutofstock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool?>("NoIndex")
                        .HasColumnType("boolean")
                        .HasColumnName("noindex");

                    b.Property<DateTimeOffset>("OnlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onlinedate");

                    b.Property<int>("ShortId")
                        .HasColumnType("integer")
                        .HasColumnName("shortid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpperDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upperdescription");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<bool?>("UseFriendlyUrl")
                        .HasColumnType("boolean")
                        .HasColumnName("usefriendlyurl");

                    b.HasKey("Sku", "VersionId", "CurrencyCode")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.OwnsOne("ProductsMicroservice.FullRelational.Family", "Family", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<long>("ProductVersionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProductCurrencyCode")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductSku", "ProductVersionId", "ProductCurrencyCode");

                            b1.ToTable("products");

                            b1.ToJson("family");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku", "ProductVersionId", "ProductCurrencyCode")
                                .HasConstraintName("fk_products_products_sku_versionid_currencycode");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.ProductionInfo", "ProductionInfo", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<long>("ProductVersionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProductCurrencyCode")
                                .HasColumnType("text");

                            b1.Property<bool>("IsNonEnglishInscription")
                                .HasColumnType("boolean");

                            b1.Property<string>("ProductSize")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("SupplierId")
                                .HasColumnType("integer");

                            b1.Property<string>("SupplierProductId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("numeric");

                            b1.HasKey("ProductSku", "ProductVersionId", "ProductCurrencyCode");

                            b1.ToTable("products");

                            b1.ToJson("productioninfo");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku", "ProductVersionId", "ProductCurrencyCode")
                                .HasConstraintName("fk_products_products_sku_versionid_currencycode");

                            b1.OwnsOne("ProductsMicroservice.FullRelational.BoxSize", "BoxSize", b2 =>
                                {
                                    b2.Property<string>("ProductionInfoProductSku")
                                        .HasColumnType("text");

                                    b2.Property<long>("ProductionInfoProductVersionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ProductionInfoProductCurrencyCode")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode");

                                    b2.ToTable("products");

                                    b2.ToJson("productioninfo");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode")
                                        .HasConstraintName("fk_products_products_productioninfoproductsku_productioninfopr~");
                                });

                            b1.OwnsOne("ProductsMicroservice.FullRelational.ProductSizeHsCode", "ProductSizeHsCode", b2 =>
                                {
                                    b2.Property<string>("ProductionInfoProductSku")
                                        .HasColumnType("text");

                                    b2.Property<long>("ProductionInfoProductVersionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ProductionInfoProductCurrencyCode")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode");

                                    b2.ToTable("products");

                                    b2.ToJson("productioninfo");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode")
                                        .HasConstraintName("fk_products_products_productioninfoproductsku_productioninfopr~");
                                });

                            b1.Navigation("BoxSize");

                            b1.Navigation("ProductSizeHsCode");
                        });

                    b.Navigation("Family")
                        .IsRequired();

                    b.Navigation("ProductionInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
