// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsMicroservice;

#nullable disable

namespace ProductsMicroservice.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240703113126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Category", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.Property<string>("CartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cartname");

                    b.Property<string>("DisplayType")
                        .HasColumnType("text")
                        .HasColumnName("displaytype");

                    b.Property<string>("EnglishCartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("englishcartname");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("englishname");

                    b.Property<int?>("GlossaryId")
                        .HasColumnType("integer")
                        .HasColumnName("glossaryid");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("isrequired");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("ProductUid")
                        .HasColumnType("integer")
                        .HasColumnName("productuid");

                    b.Property<bool>("TextIsMultiline")
                        .HasColumnType("boolean")
                        .HasColumnName("textismultiline");

                    b.Property<int?>("TextMaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("textmaxlength");

                    b.Property<int?>("TextMinLength")
                        .HasColumnType("integer")
                        .HasColumnName("textminlength");

                    b.Property<string>("TextPlaceholder")
                        .HasColumnType("text")
                        .HasColumnName("textplaceholder");

                    b.Property<int?>("TooltipId")
                        .HasColumnType("integer")
                        .HasColumnName("tooltipid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Uid")
                        .HasName("pk_category");

                    b.HasIndex("ProductUid")
                        .HasDatabaseName("ix_category_productuid");

                    b.HasIndex("Uid")
                        .HasDatabaseName("ix_category_uid");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("ProductUid")
                        .HasColumnType("integer")
                        .HasColumnName("productuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_field");

                    b.HasIndex("ProductUid")
                        .HasDatabaseName("ix_field_productuid");

                    b.ToTable("field", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Label", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CategoryUid")
                        .HasColumnType("text")
                        .HasColumnName("categoryuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "CategoryUid")
                        .HasName("pk_label");

                    b.HasIndex("CategoryUid")
                        .HasDatabaseName("ix_label_categoryuid");

                    b.ToTable("label", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Option", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CategoryUid")
                        .HasColumnType("text")
                        .HasColumnName("categoryuid");

                    b.Property<string>("CartDisplayType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cartdisplaytype");

                    b.Property<string>("CartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cartname");

                    b.Property<string>("EnglishCartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("englishcartname");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("englishname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isdefault");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("boolean")
                        .HasColumnName("isplaceholder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("numeric")
                        .HasColumnName("priceadjustment");

                    b.Property<bool>("UsePriceAdjustmentInName")
                        .HasColumnType("boolean")
                        .HasColumnName("usepriceadjustmentinname");

                    b.HasKey("Id", "CategoryUid")
                        .HasName("pk_option");

                    b.HasIndex("CategoryUid")
                        .HasDatabaseName("ix_option_categoryuid");

                    b.ToTable("option", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("uid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Uid"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currencycode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string[]>("ExcludedCountries")
                        .HasColumnType("text[]")
                        .HasColumnName("excludedcountries");

                    b.Property<string>("FriendlyUrl")
                        .HasColumnType("text")
                        .HasColumnName("friendlyurl");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("isarchived");

                    b.Property<bool>("IsDiamond")
                        .HasColumnType("boolean")
                        .HasColumnName("isdiamond");

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("isoutofstock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool?>("NoIndex")
                        .HasColumnType("boolean")
                        .HasColumnName("noindex");

                    b.Property<DateTimeOffset>("OnlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onlinedate");

                    b.Property<int>("ShortId")
                        .HasColumnType("integer")
                        .HasColumnName("shortid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpperDescription")
                        .HasColumnType("text")
                        .HasColumnName("upperdescription");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<bool?>("UseFriendlyUrl")
                        .HasColumnType("boolean")
                        .HasColumnName("usefriendlyurl");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("versionid");

                    b.HasKey("Uid")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .HasDatabaseName("ix_products_sku");

                    b.HasIndex("Uid")
                        .HasDatabaseName("ix_products_uid");

                    b.HasIndex("Sku", "VersionId", "CurrencyCode")
                        .HasDatabaseName("ix_products_sku_versionid_currencycode");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductUid")
                        .HasColumnType("integer")
                        .HasColumnName("productuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_relationship");

                    b.HasIndex("ProductUid")
                        .HasDatabaseName("ix_relationship_productuid");

                    b.ToTable("relationship", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.RelationshipProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyUrl")
                        .HasColumnType("text")
                        .HasColumnName("friendlyurl");

                    b.Property<List<string>>("RelatedCategoryUids")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("relatedcategoryuids");

                    b.Property<List<string>>("RelatedChildCategoryUids")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("relatedchildcategoryuids");

                    b.Property<int>("RelationshipId")
                        .HasColumnType("integer")
                        .HasColumnName("relationshipid");

                    b.Property<int>("ShortId")
                        .HasColumnType("integer")
                        .HasColumnName("shortid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<bool?>("UseFriendlyUrl")
                        .HasColumnType("boolean")
                        .HasColumnName("usefriendlyurl");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("versionid");

                    b.HasKey("Id")
                        .HasName("pk_relationshipproduct");

                    b.HasIndex("RelationshipId")
                        .HasDatabaseName("ix_relationshipproduct_relationshipid");

                    b.ToTable("relationshipproduct", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.ShowAndHide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<int>>("ControlledCategories")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("controlledcategories");

                    b.Property<List<string>>("ControlledCategoryKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("controlledcategorykeys");

                    b.Property<int>("ControllingCategory")
                        .HasColumnType("integer")
                        .HasColumnName("controllingcategory");

                    b.Property<string>("ControllingCategoryKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("controllingcategorykey");

                    b.Property<int>("ControllingOption")
                        .HasColumnType("integer")
                        .HasColumnName("controllingoption");

                    b.Property<int>("ProductUid")
                        .HasColumnType("integer")
                        .HasColumnName("productuid");

                    b.HasKey("Id")
                        .HasName("pk_showandhide");

                    b.HasIndex("ProductUid")
                        .HasDatabaseName("ix_showandhide_productuid");

                    b.ToTable("showandhide", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Category", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Product", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProductUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_products_productuid");

                    b.OwnsOne("ProductsMicroservice.FullRelational.Image", "CustomizationTemplate", b1 =>
                        {
                            b1.Property<string>("CategoryUid")
                                .HasColumnType("text")
                                .HasColumnName("uid");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("customizationtemplate_url");

                            b1.HasKey("CategoryUid");

                            b1.ToTable("category");

                            b1.WithOwner()
                                .HasForeignKey("CategoryUid")
                                .HasConstraintName("fk_category_category_uid");
                        });

                    b.Navigation("CustomizationTemplate");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Field", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Product", null)
                        .WithMany("Fields")
                        .HasForeignKey("ProductUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_products_productuid");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Label", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Category", null)
                        .WithMany("Labels")
                        .HasForeignKey("CategoryUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_label_category_categoryuid");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Option", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Category", null)
                        .WithMany("Options")
                        .HasForeignKey("CategoryUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_option_category_categoryuid");

                    b.OwnsOne("ProductsMicroservice.FullRelational.Image", "Image", b1 =>
                        {
                            b1.Property<int>("OptionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("OptionCategoryUid")
                                .HasColumnType("text")
                                .HasColumnName("categoryuid");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.HasKey("OptionId", "OptionCategoryUid");

                            b1.ToTable("option");

                            b1.WithOwner()
                                .HasForeignKey("OptionId", "OptionCategoryUid")
                                .HasConstraintName("fk_option_option_id_categoryuid");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.SwitchProduct", "RelatedProduct", b1 =>
                        {
                            b1.Property<int>("OptionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("OptionCategoryUid")
                                .HasColumnType("text")
                                .HasColumnName("categoryuid");

                            b1.Property<string[]>("ExcludedCountries")
                                .HasColumnType("text[]")
                                .HasColumnName("relatedproduct_excludedcountries");

                            b1.Property<string>("FriendlyUrl")
                                .HasColumnType("text")
                                .HasColumnName("relatedproduct_friendlyurl");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("relatedproduct_id");

                            b1.Property<int?>("ShortId")
                                .HasColumnType("integer")
                                .HasColumnName("relatedproduct_shortid");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("relatedproduct_sku");

                            b1.HasKey("OptionId", "OptionCategoryUid");

                            b1.ToTable("option");

                            b1.WithOwner()
                                .HasForeignKey("OptionId", "OptionCategoryUid")
                                .HasConstraintName("fk_option_option_id_categoryuid");

                            b1.OwnsOne("ProductsMicroservice.FullRelational.RelatedProductPricing", "Pricing", b2 =>
                                {
                                    b2.Property<int>("SwitchProductOptionId")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<string>("SwitchProductOptionCategoryUid")
                                        .HasColumnType("text")
                                        .HasColumnName("categoryuid");

                                    b2.Property<decimal>("Price")
                                        .HasColumnType("numeric")
                                        .HasColumnName("relatedproduct_pricing_price");

                                    b2.Property<string>("PricingType")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("relatedproduct_pricing_pricingtype");

                                    b2.HasKey("SwitchProductOptionId", "SwitchProductOptionCategoryUid");

                                    b2.ToTable("option");

                                    b2.WithOwner()
                                        .HasForeignKey("SwitchProductOptionId", "SwitchProductOptionCategoryUid")
                                        .HasConstraintName("fk_option_option_id_categoryuid");
                                });

                            b1.Navigation("Pricing")
                                .IsRequired();
                        });

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("RelatedProduct");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.OwnsOne("ProductsMicroservice.FullRelational.Family", "Family", b1 =>
                        {
                            b1.Property<int>("ProductUid")
                                .HasColumnType("integer")
                                .HasColumnName("uid");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("family_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("family_name");

                            b1.HasKey("ProductUid");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductUid")
                                .HasConstraintName("fk_products_products_uid");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("ProductUid")
                                .HasColumnType("integer")
                                .HasColumnName("uid");

                            b1.Property<string>("SchemaVersion")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("metadata_schemaversion");

                            b1.HasKey("ProductUid");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductUid")
                                .HasConstraintName("fk_products_products_uid");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.ProductMedia", "Media", b1 =>
                        {
                            b1.Property<int>("ProductUid")
                                .HasColumnType("integer")
                                .HasColumnName("uid");

                            b1.Property<int?>("DefaultItemId")
                                .HasColumnType("integer")
                                .HasColumnName("media_defaultitemid");

                            b1.Property<int?>("OverlayItemId")
                                .HasColumnType("integer")
                                .HasColumnName("media_overlayitemid");

                            b1.HasKey("ProductUid");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductUid")
                                .HasConstraintName("fk_products_products_uid");

                            b1.OwnsMany("ProductsMicroservice.FullRelational.DigitalAsset", "Items", b2 =>
                                {
                                    b2.Property<int>("ProductUid")
                                        .HasColumnType("integer")
                                        .HasColumnName("productuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Alt")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("alt");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer")
                                        .HasColumnName("order");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("title");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("type");

                                    b2.HasKey("ProductUid", "Id")
                                        .HasName("pk_digitalasset");

                                    b2.HasIndex("ProductUid")
                                        .HasDatabaseName("ix_digitalasset_productuid");

                                    b2.ToTable("digitalasset", (string)null);

                                    b2.WithOwner("Media")
                                        .HasForeignKey("ProductUid")
                                        .HasConstraintName("fk_digitalasset_products_productuid");

                                    b2.OwnsOne("ProductsMicroservice.FullRelational.CdnImageDimensions", "CdnImages", b3 =>
                                        {
                                            b3.Property<int>("DigitalAssetProductUid")
                                                .HasColumnType("integer")
                                                .HasColumnName("productuid");

                                            b3.Property<int>("DigitalAssetId")
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            b3.HasKey("DigitalAssetProductUid", "DigitalAssetId");

                                            b3.ToTable("digitalasset");

                                            b3.WithOwner()
                                                .HasForeignKey("DigitalAssetProductUid", "DigitalAssetId")
                                                .HasConstraintName("fk_digitalasset_digitalasset_productuid_id");

                                            b3.OwnsOne("ProductsMicroservice.FullRelational.CdnImage", "Medium", b4 =>
                                                {
                                                    b4.Property<int>("CdnImageDimensionsDigitalAssetProductUid")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("productuid");

                                                    b4.Property<int>("CdnImageDimensionsDigitalAssetId")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("id");

                                                    b4.Property<int>("Height")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_medium_height");

                                                    b4.Property<string>("Path")
                                                        .IsRequired()
                                                        .HasColumnType("text")
                                                        .HasColumnName("cdnimages_medium_path");

                                                    b4.Property<int>("Width")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_medium_width");

                                                    b4.HasKey("CdnImageDimensionsDigitalAssetProductUid", "CdnImageDimensionsDigitalAssetId");

                                                    b4.ToTable("digitalasset");

                                                    b4.WithOwner()
                                                        .HasForeignKey("CdnImageDimensionsDigitalAssetProductUid", "CdnImageDimensionsDigitalAssetId")
                                                        .HasConstraintName("fk_digitalasset_digitalasset_productuid_id");
                                                });

                                            b3.OwnsOne("ProductsMicroservice.FullRelational.CdnImage", "Original", b4 =>
                                                {
                                                    b4.Property<int>("CdnImageDimensionsDigitalAssetProductUid")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("productuid");

                                                    b4.Property<int>("CdnImageDimensionsDigitalAssetId")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("id");

                                                    b4.Property<int>("Height")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_original_height");

                                                    b4.Property<string>("Path")
                                                        .IsRequired()
                                                        .HasColumnType("text")
                                                        .HasColumnName("cdnimages_original_path");

                                                    b4.Property<int>("Width")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_original_width");

                                                    b4.HasKey("CdnImageDimensionsDigitalAssetProductUid", "CdnImageDimensionsDigitalAssetId");

                                                    b4.ToTable("digitalasset");

                                                    b4.WithOwner()
                                                        .HasForeignKey("CdnImageDimensionsDigitalAssetProductUid", "CdnImageDimensionsDigitalAssetId")
                                                        .HasConstraintName("fk_digitalasset_digitalasset_productuid_id");
                                                });

                                            b3.Navigation("Medium");

                                            b3.Navigation("Original");
                                        });

                                    b2.OwnsOne("ProductsMicroservice.FullRelational.WistiaVideo", "ThreeSixtyWistiaVideo", b3 =>
                                        {
                                            b3.Property<int>("DigitalAssetProductUid")
                                                .HasColumnType("integer")
                                                .HasColumnName("productuid");

                                            b3.Property<int>("DigitalAssetId")
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            b3.Property<string>("Key")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("threesixtywistiavideo_key");

                                            b3.HasKey("DigitalAssetProductUid", "DigitalAssetId");

                                            b3.ToTable("digitalasset");

                                            b3.WithOwner()
                                                .HasForeignKey("DigitalAssetProductUid", "DigitalAssetId")
                                                .HasConstraintName("fk_digitalasset_digitalasset_productuid_id");
                                        });

                                    b2.OwnsOne("ProductsMicroservice.FullRelational.WistiaVideo", "WistiaVideo", b3 =>
                                        {
                                            b3.Property<int>("DigitalAssetProductUid")
                                                .HasColumnType("integer")
                                                .HasColumnName("productuid");

                                            b3.Property<int>("DigitalAssetId")
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            b3.Property<string>("Key")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("wistiavideo_key");

                                            b3.HasKey("DigitalAssetProductUid", "DigitalAssetId");

                                            b3.ToTable("digitalasset");

                                            b3.WithOwner()
                                                .HasForeignKey("DigitalAssetProductUid", "DigitalAssetId")
                                                .HasConstraintName("fk_digitalasset_digitalasset_productuid_id");
                                        });

                                    b2.Navigation("CdnImages")
                                        .IsRequired();

                                    b2.Navigation("Media");

                                    b2.Navigation("ThreeSixtyWistiaVideo");

                                    b2.Navigation("WistiaVideo");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.ProductPricing", "Pricing", b1 =>
                        {
                            b1.Property<int>("ProductUid")
                                .HasColumnType("integer")
                                .HasColumnName("uid");

                            b1.Property<decimal?>("BasePrice")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_baseprice");

                            b1.Property<decimal?>("CrossedPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_crossedprice");

                            b1.Property<decimal?>("DiscountPercentage")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_discountpercentage");

                            b1.Property<string>("PriceElements")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pricing_priceelements");

                            b1.Property<decimal>("SellingPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_sellingprice");

                            b1.Property<decimal?>("SupplierPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("pricing_supplierprice");

                            b1.HasKey("ProductUid");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductUid")
                                .HasConstraintName("fk_products_products_uid");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.ProductionInfo", "ProductionInfo", b1 =>
                        {
                            b1.Property<int>("ProductUid")
                                .HasColumnType("integer")
                                .HasColumnName("uid");

                            b1.Property<bool>("IsNonEnglishInscription")
                                .HasColumnType("boolean")
                                .HasColumnName("productioninfo_isnonenglishinscription");

                            b1.Property<string>("ProductSize")
                                .HasColumnType("text")
                                .HasColumnName("productioninfo_productsize");

                            b1.Property<int>("SupplierId")
                                .HasColumnType("integer")
                                .HasColumnName("productioninfo_supplierid");

                            b1.Property<string>("SupplierProductId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("productioninfo_supplierproductid");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("numeric")
                                .HasColumnName("productioninfo_weight");

                            b1.HasKey("ProductUid");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductUid")
                                .HasConstraintName("fk_products_products_uid");

                            b1.OwnsOne("ProductsMicroservice.FullRelational.BoxSize", "BoxSize", b2 =>
                                {
                                    b2.Property<int>("ProductionInfoProductUid")
                                        .HasColumnType("integer")
                                        .HasColumnName("uid");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer")
                                        .HasColumnName("productioninfo_boxsize_id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("productioninfo_boxsize_name");

                                    b2.HasKey("ProductionInfoProductUid");

                                    b2.ToTable("products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductionInfoProductUid")
                                        .HasConstraintName("fk_products_products_uid");
                                });

                            b1.OwnsOne("ProductsMicroservice.FullRelational.ProductSizeHsCode", "ProductSizeHsCode", b2 =>
                                {
                                    b2.Property<int>("ProductionInfoProductUid")
                                        .HasColumnType("integer")
                                        .HasColumnName("uid");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer")
                                        .HasColumnName("productioninfo_productsizehscode_id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("productioninfo_productsizehscode_name");

                                    b2.HasKey("ProductionInfoProductUid");

                                    b2.ToTable("products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductionInfoProductUid")
                                        .HasConstraintName("fk_products_products_uid");
                                });

                            b1.Navigation("BoxSize");

                            b1.Navigation("ProductSizeHsCode");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.Site", "Site", b1 =>
                        {
                            b1.Property<int>("ProductUid")
                                .HasColumnType("integer")
                                .HasColumnName("uid");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("site_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("site_name");

                            b1.HasKey("ProductUid");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductUid")
                                .HasConstraintName("fk_products_products_uid");

                            b1.OwnsOne("ProductsMicroservice.FullRelational.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("SiteProductUid")
                                        .HasColumnType("integer")
                                        .HasColumnName("uid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("site_currency_code");

                                    b2.Property<string>("Side")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("site_currency_side");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("site_currency_symbol");

                                    b2.HasKey("SiteProductUid");

                                    b2.ToTable("products");

                                    b2.WithOwner()
                                        .HasForeignKey("SiteProductUid")
                                        .HasConstraintName("fk_products_products_uid");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Family")
                        .IsRequired();

                    b.Navigation("Media")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();

                    b.Navigation("ProductionInfo");

                    b.Navigation("Site")
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Relationship", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Product", null)
                        .WithMany("Relationships")
                        .HasForeignKey("ProductUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationship_products_productuid");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.RelationshipProduct", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Relationship", null)
                        .WithMany("RelatedProducts")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationshipproduct_relationship_relationshipid");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.ShowAndHide", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Product", null)
                        .WithMany("ShowAndHides")
                        .HasForeignKey("ProductUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_showandhide_products_productuid");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Category", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Fields");

                    b.Navigation("Relationships");

                    b.Navigation("ShowAndHides");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Relationship", b =>
                {
                    b.Navigation("RelatedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
