// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsMicroservice;

#nullable disable

namespace ProductsMicroservice.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240702120236_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("versionid");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currencycode");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OnlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onlinedate");

                    b.Property<int>("ShortId")
                        .HasColumnType("integer")
                        .HasColumnName("shortid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Sku", "VersionId", "CurrencyCode")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.OwnsOne("ProductsMicroservice.FullRelational.Family", "Family", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<long>("ProductVersionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProductCurrencyCode")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductSku", "ProductVersionId", "ProductCurrencyCode");

                            b1.ToTable("products");

                            b1.ToJson("family");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku", "ProductVersionId", "ProductCurrencyCode")
                                .HasConstraintName("fk_products_products_sku_versionid_currencycode");
                        });

                    b.Navigation("Family")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
