// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsMicroservice;

#nullable disable

namespace ProductsMicroservice.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240702152627_InitialCreate13")]
    partial class InitialCreate13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("versionid");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currencycode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string[]>("ExcludedCountries")
                        .HasColumnType("text[]")
                        .HasColumnName("excludedcountries");

                    b.Property<string>("FriendlyUrl")
                        .HasColumnType("text")
                        .HasColumnName("friendlyurl");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("isarchived");

                    b.Property<bool>("IsDiamond")
                        .HasColumnType("boolean")
                        .HasColumnName("isdiamond");

                    b.Property<bool>("IsOutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("isoutofstock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool?>("NoIndex")
                        .HasColumnType("boolean")
                        .HasColumnName("noindex");

                    b.Property<DateTimeOffset>("OnlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onlinedate");

                    b.Property<int>("ShortId")
                        .HasColumnType("integer")
                        .HasColumnName("shortid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpperDescription")
                        .HasColumnType("text")
                        .HasColumnName("upperdescription");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<bool?>("UseFriendlyUrl")
                        .HasColumnType("boolean")
                        .HasColumnName("usefriendlyurl");

                    b.HasKey("Sku", "VersionId", "CurrencyCode")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .HasDatabaseName("ix_products_sku");

                    b.HasIndex("Sku", "VersionId", "CurrencyCode")
                        .HasDatabaseName("ix_products_sku_versionid_currencycode");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Ribbon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currencycode");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("versionid");

                    b.HasKey("Id")
                        .HasName("pk_ribbon");

                    b.HasIndex("Sku", "VersionId", "CurrencyCode")
                        .HasDatabaseName("ix_ribbon_sku_versionid_currencycode");

                    b.ToTable("ribbon", (string)null);
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.OwnsOne("ProductsMicroservice.FullRelational.Family", "Family", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<long>("ProductVersionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProductCurrencyCode")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductSku", "ProductVersionId", "ProductCurrencyCode");

                            b1.ToTable("products");

                            b1.ToJson("family");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku", "ProductVersionId", "ProductCurrencyCode")
                                .HasConstraintName("fk_products_products_sku_versionid_currencycode");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.ProductMedia", "Media", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text")
                                .HasColumnName("sku");

                            b1.Property<long>("ProductVersionId")
                                .HasColumnType("bigint")
                                .HasColumnName("versionid");

                            b1.Property<string>("ProductCurrencyCode")
                                .HasColumnType("text")
                                .HasColumnName("currencycode");

                            b1.Property<int?>("DefaultItemId")
                                .HasColumnType("integer")
                                .HasColumnName("media_defaultitemid");

                            b1.Property<int?>("OverlayItemId")
                                .HasColumnType("integer")
                                .HasColumnName("media_overlayitemid");

                            b1.HasKey("ProductSku", "ProductVersionId", "ProductCurrencyCode");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku", "ProductVersionId", "ProductCurrencyCode")
                                .HasConstraintName("fk_products_products_sku_versionid_currencycode");

                            b1.OwnsMany("ProductsMicroservice.FullRelational.DigitalAsset", "Items", b2 =>
                                {
                                    b2.Property<string>("Sku")
                                        .HasColumnType("text")
                                        .HasColumnName("sku");

                                    b2.Property<long>("VersionId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("versionid");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnType("text")
                                        .HasColumnName("currencycode");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Alt")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("alt");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer")
                                        .HasColumnName("order");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("title");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("type");

                                    b2.HasKey("Sku", "VersionId", "CurrencyCode", "Id")
                                        .HasName("pk_digitalasset");

                                    b2.HasIndex("Sku", "VersionId", "CurrencyCode")
                                        .HasDatabaseName("ix_digitalasset_sku_versionid_currencycode");

                                    b2.ToTable("digitalasset", (string)null);

                                    b2.WithOwner("Media")
                                        .HasForeignKey("Sku", "VersionId", "CurrencyCode")
                                        .HasConstraintName("fk_digitalasset_products_sku_versionid_currencycode");

                                    b2.OwnsOne("ProductsMicroservice.FullRelational.CdnImageDimensions", "CdnImages", b3 =>
                                        {
                                            b3.Property<string>("DigitalAssetSku")
                                                .HasColumnType("text")
                                                .HasColumnName("sku");

                                            b3.Property<long>("DigitalAssetVersionId")
                                                .HasColumnType("bigint")
                                                .HasColumnName("versionid");

                                            b3.Property<string>("DigitalAssetCurrencyCode")
                                                .HasColumnType("text")
                                                .HasColumnName("currencycode");

                                            b3.Property<int>("DigitalAssetId")
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            b3.HasKey("DigitalAssetSku", "DigitalAssetVersionId", "DigitalAssetCurrencyCode", "DigitalAssetId");

                                            b3.ToTable("digitalasset");

                                            b3.WithOwner()
                                                .HasForeignKey("DigitalAssetSku", "DigitalAssetVersionId", "DigitalAssetCurrencyCode", "DigitalAssetId")
                                                .HasConstraintName("fk_digitalasset_digitalasset_sku_versionid_currencycode_id");

                                            b3.OwnsOne("ProductsMicroservice.FullRelational.CdnImage", "Medium", b4 =>
                                                {
                                                    b4.Property<string>("CdnImageDimensionsDigitalAssetSku")
                                                        .HasColumnType("text")
                                                        .HasColumnName("sku");

                                                    b4.Property<long>("CdnImageDimensionsDigitalAssetVersionId")
                                                        .HasColumnType("bigint")
                                                        .HasColumnName("versionid");

                                                    b4.Property<string>("CdnImageDimensionsDigitalAssetCurrencyCode")
                                                        .HasColumnType("text")
                                                        .HasColumnName("currencycode");

                                                    b4.Property<int>("CdnImageDimensionsDigitalAssetId")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("id");

                                                    b4.Property<int>("Height")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_medium_height");

                                                    b4.Property<string>("Path")
                                                        .IsRequired()
                                                        .HasColumnType("text")
                                                        .HasColumnName("cdnimages_medium_path");

                                                    b4.Property<int>("Width")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_medium_width");

                                                    b4.HasKey("CdnImageDimensionsDigitalAssetSku", "CdnImageDimensionsDigitalAssetVersionId", "CdnImageDimensionsDigitalAssetCurrencyCode", "CdnImageDimensionsDigitalAssetId");

                                                    b4.ToTable("digitalasset");

                                                    b4.WithOwner()
                                                        .HasForeignKey("CdnImageDimensionsDigitalAssetSku", "CdnImageDimensionsDigitalAssetVersionId", "CdnImageDimensionsDigitalAssetCurrencyCode", "CdnImageDimensionsDigitalAssetId")
                                                        .HasConstraintName("fk_digitalasset_digitalasset_sku_versionid_currencycode_id");
                                                });

                                            b3.OwnsOne("ProductsMicroservice.FullRelational.CdnImage", "Original", b4 =>
                                                {
                                                    b4.Property<string>("CdnImageDimensionsDigitalAssetSku")
                                                        .HasColumnType("text")
                                                        .HasColumnName("sku");

                                                    b4.Property<long>("CdnImageDimensionsDigitalAssetVersionId")
                                                        .HasColumnType("bigint")
                                                        .HasColumnName("versionid");

                                                    b4.Property<string>("CdnImageDimensionsDigitalAssetCurrencyCode")
                                                        .HasColumnType("text")
                                                        .HasColumnName("currencycode");

                                                    b4.Property<int>("CdnImageDimensionsDigitalAssetId")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("id");

                                                    b4.Property<int>("Height")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_original_height");

                                                    b4.Property<string>("Path")
                                                        .IsRequired()
                                                        .HasColumnType("text")
                                                        .HasColumnName("cdnimages_original_path");

                                                    b4.Property<int>("Width")
                                                        .HasColumnType("integer")
                                                        .HasColumnName("cdnimages_original_width");

                                                    b4.HasKey("CdnImageDimensionsDigitalAssetSku", "CdnImageDimensionsDigitalAssetVersionId", "CdnImageDimensionsDigitalAssetCurrencyCode", "CdnImageDimensionsDigitalAssetId");

                                                    b4.ToTable("digitalasset");

                                                    b4.WithOwner()
                                                        .HasForeignKey("CdnImageDimensionsDigitalAssetSku", "CdnImageDimensionsDigitalAssetVersionId", "CdnImageDimensionsDigitalAssetCurrencyCode", "CdnImageDimensionsDigitalAssetId")
                                                        .HasConstraintName("fk_digitalasset_digitalasset_sku_versionid_currencycode_id");
                                                });

                                            b3.Navigation("Medium")
                                                .IsRequired();

                                            b3.Navigation("Original")
                                                .IsRequired();
                                        });

                                    b2.OwnsOne("ProductsMicroservice.FullRelational.WistiaVideo", "ThreeSixtyWistiaVideo", b3 =>
                                        {
                                            b3.Property<string>("DigitalAssetSku")
                                                .HasColumnType("text")
                                                .HasColumnName("sku");

                                            b3.Property<long>("DigitalAssetVersionId")
                                                .HasColumnType("bigint")
                                                .HasColumnName("versionid");

                                            b3.Property<string>("DigitalAssetCurrencyCode")
                                                .HasColumnType("text")
                                                .HasColumnName("currencycode");

                                            b3.Property<int>("DigitalAssetId")
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            b3.Property<string>("Key")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("threesixtywistiavideo_key");

                                            b3.HasKey("DigitalAssetSku", "DigitalAssetVersionId", "DigitalAssetCurrencyCode", "DigitalAssetId");

                                            b3.ToTable("digitalasset");

                                            b3.WithOwner()
                                                .HasForeignKey("DigitalAssetSku", "DigitalAssetVersionId", "DigitalAssetCurrencyCode", "DigitalAssetId")
                                                .HasConstraintName("fk_digitalasset_digitalasset_sku_versionid_currencycode_id");
                                        });

                                    b2.OwnsOne("ProductsMicroservice.FullRelational.WistiaVideo", "WistiaVideo", b3 =>
                                        {
                                            b3.Property<string>("DigitalAssetSku")
                                                .HasColumnType("text")
                                                .HasColumnName("sku");

                                            b3.Property<long>("DigitalAssetVersionId")
                                                .HasColumnType("bigint")
                                                .HasColumnName("versionid");

                                            b3.Property<string>("DigitalAssetCurrencyCode")
                                                .HasColumnType("text")
                                                .HasColumnName("currencycode");

                                            b3.Property<int>("DigitalAssetId")
                                                .HasColumnType("integer")
                                                .HasColumnName("id");

                                            b3.Property<string>("Key")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("wistiavideo_key");

                                            b3.HasKey("DigitalAssetSku", "DigitalAssetVersionId", "DigitalAssetCurrencyCode", "DigitalAssetId");

                                            b3.ToTable("digitalasset");

                                            b3.WithOwner()
                                                .HasForeignKey("DigitalAssetSku", "DigitalAssetVersionId", "DigitalAssetCurrencyCode", "DigitalAssetId")
                                                .HasConstraintName("fk_digitalasset_digitalasset_sku_versionid_currencycode_id");
                                        });

                                    b2.Navigation("CdnImages")
                                        .IsRequired();

                                    b2.Navigation("Media");

                                    b2.Navigation("ThreeSixtyWistiaVideo");

                                    b2.Navigation("WistiaVideo");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("ProductsMicroservice.FullRelational.ProductionInfo", "ProductionInfo", b1 =>
                        {
                            b1.Property<string>("ProductSku")
                                .HasColumnType("text");

                            b1.Property<long>("ProductVersionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProductCurrencyCode")
                                .HasColumnType("text");

                            b1.Property<bool>("IsNonEnglishInscription")
                                .HasColumnType("boolean");

                            b1.Property<string>("ProductSize")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("SupplierId")
                                .HasColumnType("integer");

                            b1.Property<string>("SupplierProductId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("numeric");

                            b1.HasKey("ProductSku", "ProductVersionId", "ProductCurrencyCode");

                            b1.ToTable("products");

                            b1.ToJson("productioninfo");

                            b1.WithOwner()
                                .HasForeignKey("ProductSku", "ProductVersionId", "ProductCurrencyCode")
                                .HasConstraintName("fk_products_products_sku_versionid_currencycode");

                            b1.OwnsOne("ProductsMicroservice.FullRelational.BoxSize", "BoxSize", b2 =>
                                {
                                    b2.Property<string>("ProductionInfoProductSku")
                                        .HasColumnType("text");

                                    b2.Property<long>("ProductionInfoProductVersionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ProductionInfoProductCurrencyCode")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode");

                                    b2.ToTable("products");

                                    b2.ToJson("productioninfo");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode")
                                        .HasConstraintName("fk_products_products_productioninfoproductsku_productioninfopr~");
                                });

                            b1.OwnsOne("ProductsMicroservice.FullRelational.ProductSizeHsCode", "ProductSizeHsCode", b2 =>
                                {
                                    b2.Property<string>("ProductionInfoProductSku")
                                        .HasColumnType("text");

                                    b2.Property<long>("ProductionInfoProductVersionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ProductionInfoProductCurrencyCode")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode");

                                    b2.ToTable("products");

                                    b2.ToJson("productioninfo");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductionInfoProductSku", "ProductionInfoProductVersionId", "ProductionInfoProductCurrencyCode")
                                        .HasConstraintName("fk_products_products_productioninfoproductsku_productioninfopr~");
                                });

                            b1.Navigation("BoxSize");

                            b1.Navigation("ProductSizeHsCode");
                        });

                    b.Navigation("Family")
                        .IsRequired();

                    b.Navigation("Media")
                        .IsRequired();

                    b.Navigation("ProductionInfo");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Ribbon", b =>
                {
                    b.HasOne("ProductsMicroservice.FullRelational.Product", null)
                        .WithMany("ProductRibbons")
                        .HasForeignKey("Sku", "VersionId", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ribbon_products_sku_versionid_currencycode");
                });

            modelBuilder.Entity("ProductsMicroservice.FullRelational.Product", b =>
                {
                    b.Navigation("ProductRibbons");
                });
#pragma warning restore 612, 618
        }
    }
}
